"""S3 adapter for storing redacted extracted document text."""

import re
from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import Any, Protocol

import boto3
from botocore.exceptions import BotoCoreError, ClientError

from app.core.config import Settings, get_settings

S3_REDACTED_DOCUMENT_CONTENT_TYPE = "text/plain; charset=utf-8"
S3_SERVER_SIDE_ENCRYPTION = "AES256"

TENANT_SLUG_PATTERN = re.compile(r"^[a-z][a-z0-9-]{0,62}$")


class S3DocumentStorageUnavailableError(RuntimeError):
    """Raised when AWS cannot safely persist a redacted document copy."""


class S3Client(Protocol):
    """The small portion of the Boto3 S3 client used by this adapter."""

    def put_object(self, **kwargs: Any) -> dict[str, Any]:
        """Store one object and return S3 response metadata."""


@dataclass(frozen=True)
class S3DocumentReference:
    """Safe S3 metadata that can be recorded with a knowledge document."""

    bucket_name: str
    object_key: str
    version_id: str | None
    e_tag: str | None


def build_redacted_document_object_key(
    *,
    tenant_slug: str,
    source_path: str,
) -> str:
    """Build a server-controlled object key; never accept traversal-like paths."""
    if not TENANT_SLUG_PATTERN.fullmatch(tenant_slug):
        raise ValueError("Tenant slug must use lowercase letters, digits, and hyphens")

    normalized_source_path = source_path.strip()
    normalized_path = PurePosixPath(normalized_source_path)

    if (
        not normalized_source_path
        or "\\" in normalized_source_path
        or normalized_path.is_absolute()
        or ".." in normalized_path.parts
    ):
        raise ValueError("Source path must be a safe relative POSIX path")

    # Store extracted, redacted text rather than the original uploaded binary file.
    return f"tenants/{tenant_slug}/redacted-documents/{normalized_path.as_posix()}.txt"


class S3RedactedDocumentStore:
    """Store redacted source text in a private S3 bucket."""

    def __init__(
        self,
        *,
        bucket_name: str,
        settings: Settings | None = None,
        client: S3Client | None = None,
    ) -> None:
        if not bucket_name.strip():
            raise ValueError("S3 bucket name must not be empty")

        self._bucket_name = bucket_name.strip()
        self._settings = settings or get_settings()
        # Tests inject a fake. Local runs use the configured AWS CLI profile.
        self._client = client or self._build_client()

    def store_redacted_document(
        self,
        *,
        tenant_slug: str,
        source_path: str,
        redacted_content: str,
        content_sha256: str,
    ) -> S3DocumentReference:
        """Upload one safe text copy with explicit server-side encryption."""
        if not redacted_content.strip():
            raise ValueError("Redacted document content must not be empty")

        if not _is_sha256(content_sha256):
            raise ValueError("Document content hash must be a SHA-256 hexadecimal value")

        object_key = build_redacted_document_object_key(
            tenant_slug=tenant_slug,
            source_path=source_path,
        )

        try:
            response = self._client.put_object(
                Bucket=self._bucket_name,
                Key=object_key,
                # The source has already passed extraction and secret redaction.
                Body=redacted_content.encode("utf-8"),
                ContentType=S3_REDACTED_DOCUMENT_CONTENT_TYPE,
                ServerSideEncryption=S3_SERVER_SIDE_ENCRYPTION,
                Metadata={
                    "document-sha256": content_sha256,
                    "storage-format": "redacted-utf8-text",
                },
            )
        except (BotoCoreError, ClientError) as error:
            # Do not expose AWS account, bucket, or policy details to API clients.
            raise S3DocumentStorageUnavailableError("S3 document storage is unavailable") from error

        version_id = response.get("VersionId")
        e_tag = response.get("ETag")

        return S3DocumentReference(
            bucket_name=self._bucket_name,
            object_key=object_key,
            version_id=version_id if isinstance(version_id, str) else None,
            e_tag=e_tag if isinstance(e_tag, str) else None,
        )

    def _build_client(self) -> S3Client:
        """Create a signed local S3 client or an IAM-role client in AWS."""
        session = boto3.Session(
            profile_name=self._settings.aws_profile or None,
            region_name=self._settings.aws_region,
        )

        return session.client("s3")


def _is_sha256(value: str) -> bool:
    """Accept only the 64-character hexadecimal hashes generated by ingestion."""
    return len(value) == 64 and all(character in "0123456789abcdef" for character in value)
