"""add workspace knowledge revision

Revision ID: 20ac1cc9692f
Revises: 858592a71161
Create Date: 2026-09-18 22:14:00.282248

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20ac1cc9692f"
down_revision: str | Sequence[str] | None = "858592a71161"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tenants", sa.Column("knowledge_revision", sa.Integer(), server_default="0", nullable=False)
    )
    op.create_check_constraint(
        "ck_tenants_knowledge_revision_nonnegative", "tenants", "knowledge_revision >= 0"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_tenants_knowledge_revision_nonnegative", "tenants", type_="check")
    op.drop_column("tenants", "knowledge_revision")
    # ### end Alembic commands ###
