"""add chunk embeddings

Revision ID: c21350bfc439
Revises: 41828afa67f1
Create Date: 2026-08-12 23:45:08.576773

"""

from collections.abc import Sequence

import pgvector.sqlalchemy  # Required so Alembic can create PostgreSQL's vector(1024) column.
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c21350bfc439"
down_revision: str | Sequence[str] | None = "41828afa67f1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_chunks",
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    )
    op.add_column(
        "document_chunks", sa.Column("embedding_model", sa.String(length=255), nullable=True)
    )
    op.add_column(
        "document_chunks", sa.Column("embedding_token_count", sa.Integer(), nullable=True)
    )
    op.add_column(
        "document_chunks",
        sa.Column("embedding_created_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_check_constraint(
        "ck_document_chunks_embedding_token_count_nonnegative",
        "document_chunks",
        "embedding_token_count >= 0",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "ck_document_chunks_embedding_token_count_nonnegative", "document_chunks", type_="check"
    )
    op.drop_column("document_chunks", "embedding_created_at")
    op.drop_column("document_chunks", "embedding_token_count")
    op.drop_column("document_chunks", "embedding_model")
    op.drop_column("document_chunks", "embedding")
    # ### end Alembic commands ###
